apiVersion: 1
datasources:
  - name: DuckDB – GitHub Lake
    type: motherduck-duckdb-datasource    # <--- ÄNDRAT: nytt namn
    access: proxy
    isDefault: true
    jsonData:
      path: /app/data/dbt/github_lake.duckdb